get#/: no@index
get#/en/: en@index
get#/om-meg.html: no@om-meg
get#/en/about-me.html: en@om-meg
get#/bekreftelse.html: no@bekreftelse
get#/en/confirmation.html: en@bekreftelse
get#/ux-design.html: no@ux-design
get#/en/ux-design.html: en@ux-design
get#/frontend.html: no@frontend
get#/en/frontend.html: en@frontend
# get#/seo-marketing.html: no@seo-marketing
# get#/en/seo-marketing.html: en@seo-marketing
# get#/hosting-drift.html: no@hosting-drift
# get#/en/hosting-support.html: en@hosting-drift
